plugins {
    // see https://fabricmc.net/develop/ for new versions
    id 'net.fabricmc.fabric-loom' version '1.16-SNAPSHOT' apply false
    // see https://projects.neoforged.net/neoforged/moddevgradle for new versions
    id 'net.neoforged.moddev' version '2.0.141' apply false
    id 'org.moddedmc.wiki.toolkit' version '0.5.0'
}

allprojects {
    repositories {
        maven {
            name = "Fuzs Mod Resources"
            url = "https://raw.githubusercontent.com/Fuzss/modresources/main/maven/"
        }
        maven {
            name = "Jared's maven"
            url = "https://maven.blamejared.com/"
        }
    }
}

wiki {
    docs {
        omnicompass {
            root = file('docs/')
        }
    }
}