modLoader = "javafml"
loaderVersion = "[2,)"
issueTrackerURL = "https://github.com/PiotrO15/OmniCompass/issues"
license = "MIT"

[[mods]]
modId = "omnicompass"
version = "${version}"
displayName = "OmniCompass"
authors = "MeVerdo"
description = '''
Configurable biome and structure compasses!
'''
logoFile = "icon.png"

[[dependencies.omnicompass]]
modId = "neoforge"
type = "required"
versionRange = "[21,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.omnicompass]]
modId = "minecraft"
type = "required"
versionRange = "${minecraft_version_range}"
ordering = "NONE"
side = "BOTH"

